package ninja.amp.tradeup.collection;

import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;

import ninja.amp.tradeup.Item;

public enum Collections implements Collection {
    ALPHA(
            new Skin(Weapon.SCAR_20, "Emerald", Quality.RESTRICTED, new Range(0, 0.08)),
            new Skin(Weapon.FAMAS, "Spitfire", Quality.RESTRICTED, new Range(0.06, 0.8)),
            new Skin(Weapon.AUG, "Anodized Navy", Quality.MIL_SPEC, new Range(0.0, 0.08)),
            new Skin(Weapon.PP_BIZON, "Rust Coat", Quality.MIL_SPEC, new Range(0, 1)),
            new Skin(Weapon.MAG_7, "Hazard", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.P250, "Facets", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.SAWED_OFF, "Mosaico", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.NEGEV, "Palm", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.SSG_08, "Mayan Dreams", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.GLOCK_18, "Sand Dune", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.MP7, "Groundwater", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.XM1014, "Jungle", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.FIVE_SEVEN, "Anodized Gunmetal", Quality.CONSUMER, new Range(0, 0.08)),
            new Skin(Weapon.MP9, "Dry Season", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.TEC_9, "Tornado", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.M249, "Jungle DDPAT", Quality.CONSUMER, new Range(0.06, 0.8))),
    ARMS_DEAL(
            new Skin(Weapon.AWP, "Lightning Strike", Quality.COVERT, new Range(0, 0.08)),
            new Skin(Weapon.AK_47, "Case Hardened", Quality.CLASSIFIED, new Range(0, 1)),
            new Skin(Weapon.DESERT_EAGLE, "Hypnotic", Quality.CLASSIFIED, new Range(0, 0.08)),
            new Skin(Weapon.GLOCK_18, "Dragon Tattoo", Quality.RESTRICTED, new Range(0, 0.08)),
            new Skin(Weapon.USP_S, "Dark Water", Quality.RESTRICTED, new Range(0.1, 0.26)),
            new Skin(Weapon.M4A1_S, "Dark Water", Quality.RESTRICTED, new Range(0.1, 0.26)),
            new Skin(Weapon.AUG, "Wings", Quality.MIL_SPEC, new Range(0, 0.14)),
            new Skin(Weapon.SG_553, "Ultraviolet", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.MP7, "Skulls", Quality.MIL_SPEC, new Range(0.1, 0.26))),
    ARMS_DEAL_2(
            new Skin(Weapon.SSG_08, "Blood in the Water", Quality.COVERT, new Range(0.06, 0.2)),
            new Skin(Weapon.USP_S, "Serum", Quality.CLASSIFIED, new Range(0, 0.25)),
            new Skin(Weapon.P90, "Cold Blooded", Quality.CLASSIFIED, new Range(0, 0.08)),
            new Skin(Weapon.MP9, "Hypnotic", Quality.RESTRICTED, new Range(0, 0.08)),
            new Skin(Weapon.DUAL_BERETTAS, "Hemoglobin", Quality.RESTRICTED, new Range(0, 0.2)),
            new Skin(Weapon.FIVE_SEVEN, "Case Hardened", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.NOVA, "Graphite", Quality.RESTRICTED, new Range(0, 0.12)),
            new Skin(Weapon.M4A1_S, "Blood Tiger", Quality.MIL_SPEC, new Range(0, 0.3)),
            new Skin(Weapon.P250, "Hive", Quality.MIL_SPEC, new Range(0, 0.3)),
            new Skin(Weapon.FAMAS, "Hexane", Quality.MIL_SPEC, new Range(0, 0.4)),
            new Skin(Weapon.TEC_9, "Blue Titanium", Quality.MIL_SPEC, new Range(0, 0.04)),
            new Skin(Weapon.SCAR_20, "Crimson Web", Quality.MIL_SPEC, new Range(0.06, 0.8))),
    ARMS_DEAL_3(
            new Skin(Weapon.CZ75_AUTO, "Victoria", Quality.COVERT, new Range(0, 0.75)),
            new Skin(Weapon.CZ75_AUTO, "The Fuschia Is Now", Quality.CLASSIFIED, new Range(0, 0.4)),
            new Skin(Weapon.P250, "Undertow", Quality.CLASSIFIED, new Range(0, 0.2)),
            new Skin(Weapon.CZ75_AUTO, "Tread Plate", Quality.RESTRICTED, new Range(0, 0.2)),
            new Skin(Weapon.TEC_9, "Titanium Bit", Quality.RESTRICTED, new Range(0, 0.2)),
            new Skin(Weapon.DESERT_EAGLE, "Heirloom", Quality.RESTRICTED, new Range(0, 0.8)),
            new Skin(Weapon.FIVE_SEVEN, "Copper Galaxy", Quality.RESTRICTED, new Range(0, 0.2)),
            new Skin(Weapon.CZ75_AUTO, "Crimson Web", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.P2000, "Red FragCam", Quality.MIL_SPEC, new Range(0, 0.7)),
            new Skin(Weapon.DUAL_BERETTAS, "Panther", Quality.MIL_SPEC, new Range(0, 0.58)),
            new Skin(Weapon.USP_S, "Stainless", Quality.MIL_SPEC, new Range(0, 0.8)),
            new Skin(Weapon.GLOCK_18, "Blue Fissure", Quality.MIL_SPEC, new Range(0.06, 0.58))),
    ASSAULT(
            new Skin(Weapon.GLOCK_18, "Fade", Quality.RESTRICTED, new Range(0, 0.08)),
            new Skin(Weapon.MP9, "Bulldozer", Quality.RESTRICTED, new Range(0.06, 0.8)),
            new Skin(Weapon.AUG, "Hot Rod", Quality.MIL_SPEC, new Range(0, 0.08)),
            new Skin(Weapon.NEGEV, "Anodized Navy", Quality.MIL_SPEC, new Range(0, 0.08)),
            new Skin(Weapon.FIVE_SEVEN, "Candy Apple", Quality.INDUSTRIAL, new Range(0, 0.3)),
            new Skin(Weapon.UMP_45, "Caramel", Quality.CONSUMER, new Range(0.6, 0.8)),
            new Skin(Weapon.SG_553, "Tornado", Quality.CONSUMER, new Range(0.6, 0.8))),
    AZTEC(
            new Skin(Weapon.TEC_9, "Ossified", Quality.MIL_SPEC, new Range(0, 0.08)),
            new Skin(Weapon.M4A4, "Jungle Tiger", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.AK_47, "Jungle Spray", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.SSG_08, "Lichen Dashed", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.FIVE_SEVEN, "Jungle", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.NOVA, "Forest Leaves", Quality.CONSUMER, new Range(0.06, 0.8))),
    BAGGAGE(
            new Skin(Weapon.AK_47, "Jet Set", Quality.CLASSIFIED, new Range(0, 1)),
            new Skin(Weapon.DESERT_EAGLE, "Pilot", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.AK_47, "First Class", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.SAWED_OFF, "First Class", Quality.MIL_SPEC, new Range(0, 0.5)),
            new Skin(Weapon.USP_S, "Business Class", Quality.MIL_SPEC, new Range(0, 1)),
            new Skin(Weapon.XM1014, "Red Leather", Quality.MIL_SPEC, new Range(0, 0.56)),
            new Skin(Weapon.P90, "Leather", Quality.INDUSTRIAL, new Range(0, 1)),
            new Skin(Weapon.MAC_10, "Commuter", Quality.INDUSTRIAL, new Range(0, 1)),
            new Skin(Weapon.P2000, "Coach Class", Quality.INDUSTRIAL, new Range(0, 1)),
            new Skin(Weapon.SG_553, "Traveler", Quality.INDUSTRIAL, new Range(0, 1)),
            new Skin(Weapon.G3SG1, "Contractor", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.MP7, "Olive Plaid", Quality.CONSUMER, new Range(0, 0.58)),
            new Skin(Weapon.CZ75_AUTO, "Green Plaid", Quality.CONSUMER, new Range(0, 0.58)),
            new Skin(Weapon.MP9, "Green Plaid", Quality.CONSUMER, new Range(0, 0.58)),
            new Skin(Weapon.SSG_08, "Sand Dune", Quality.CONSUMER, new Range(0.06, 0.8))),
    BANK(
            new Skin(Weapon.P250, "Franklin", Quality.CLASSIFIED, new Range(0, 0.4)),
            new Skin(Weapon.AK_47, "Emerald Pinstripe", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.CZ75_AUTO, "Tuxedo", Quality.MIL_SPEC, new Range(0, 0.8)),
            new Skin(Weapon.DESERT_EAGLE, "Meteorite", Quality.MIL_SPEC, new Range(0, 0.18)),
            new Skin(Weapon.GALIL_AR, "Tuxedo", Quality.MIL_SPEC, new Range(0, 0.8)),
            new Skin(Weapon.G3SG1, "Green Apple", Quality.INDUSTRIAL, new Range(0, 0.3)),
            new Skin(Weapon.GLOCK_18, "Death Rattle", Quality.INDUSTRIAL, new Range(0.08, 0.5)),
            new Skin(Weapon.MAC_10, "Silver", Quality.INDUSTRIAL, new Range(0, 0.08)),
            new Skin(Weapon.NOVA, "Caged Steel", Quality.INDUSTRIAL, new Range(0, 0.2)),
            new Skin(Weapon.UMP_45, "Carbon Fiber", Quality.INDUSTRIAL, new Range(0, 0.12)),
            new Skin(Weapon.R8_REVOLVER, "Bone Mask", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.MP7, "Forest DDPAT", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.NEGEV, "Army Sheen", Quality.CONSUMER, new Range(0, 0.3)),
            new Skin(Weapon.SAWED_OFF, "Forest DDPAT", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.SG_553, "Army Sheen", Quality.CONSUMER, new Range(0, 0.3)),
            new Skin(Weapon.TEC_9, "Urban DDPAT", Quality.CONSUMER, new Range(0.06, 0.8))),
    BRAVO(
            new Skin(Weapon.AK_47, "Fire Serpent", Quality.COVERT, new Range(0, 0.12)),
            new Skin(Weapon.DESERT_EAGLE, "Golden Koi", Quality.COVERT, new Range(0.06, 0.76)),
            new Skin(Weapon.AWP, "Graphite", Quality.CLASSIFIED, new Range(0, 0.12)),
            new Skin(Weapon.P2000, "Ocean Foam", Quality.CLASSIFIED, new Range(0, 0.12)),
            new Skin(Weapon.P90, "Emerald Dragon", Quality.CLASSIFIED, new Range(0.06, 0.52)),
            new Skin(Weapon.USP_S, "Overgrowth", Quality.RESTRICTED, new Range(0.06, 0.8)),
            new Skin(Weapon.MAC_10, "Graven", Quality.RESTRICTED, new Range(0.06, 0.8)),
            new Skin(Weapon.M4A4, "Zirka", Quality.RESTRICTED, new Range(0.06, 0.42)),
            new Skin(Weapon.M4A1_S, "Bright Water", Quality.RESTRICTED, new Range(0.1, 0.22)),
            new Skin(Weapon.G3SG1, "Demeter", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.GALIL_AR, "Shattered", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.SG_553, "Wave Spray", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.UMP_45, "Bone Pile", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.DUAL_BERETTAS, "Black Limba", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.NOVA, "Tempest", Quality.MIL_SPEC, new Range(0.06, 0.22))),
    BREAKOUT(
            new Skin(Weapon.M4A1_S, "Cyrex", Quality.COVERT, new Range(0, 0.5)),
            new Skin(Weapon.P90, "Asiimov", Quality.COVERT, new Range(0, 0.92)),
            new Skin(Weapon.DESERT_EAGLE, "Conspiracy", Quality.CLASSIFIED, new Range(0, 0.3)),
            new Skin(Weapon.FIVE_SEVEN, "Fowl Play", Quality.CLASSIFIED, new Range(0, 1)),
            new Skin(Weapon.GLOCK_18, "Water Elemental", Quality.CLASSIFIED, new Range(0, 0.7)),
            new Skin(Weapon.NOVA, "Koi", Quality.RESTRICTED, new Range(0, 0.3)),
            new Skin(Weapon.P250, "Supernova", Quality.RESTRICTED, new Range(0, 0.4)),
            new Skin(Weapon.PP_BIZON, "Osiris", Quality.RESTRICTED, new Range(0, 0.5)),
            new Skin(Weapon.CZ75_AUTO, "Tigris", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.MP7, "Urban Hazard", Quality.MIL_SPEC, new Range(0, 0.5)),
            new Skin(Weapon.NEGEV, "Desert-Strike", Quality.MIL_SPEC, new Range(0, 0.5)),
            new Skin(Weapon.SSG_08, "Abyss", Quality.MIL_SPEC, new Range(0, 1)),
            new Skin(Weapon.UMP_45, "Labyrinth", Quality.MIL_SPEC, new Range(0, 0.4)),
            new Skin(Weapon.P2000, "Ivory", Quality.MIL_SPEC, new Range(0, 1))),
    CACHE(
            new Skin(Weapon.GALIL_AR, "Cerberus", Quality.RESTRICTED, new Range(0, 0.9)),
            new Skin(Weapon.FAMAS, "Styx", Quality.RESTRICTED, new Range(0, 0.6)),
            new Skin(Weapon.TEC_9, "Toxic", Quality.MIL_SPEC, new Range(0, 0.7)),
            new Skin(Weapon.GLOCK_18, "Reactor", Quality.MIL_SPEC, new Range(0, 1)),
            new Skin(Weapon.XM1014, "Bone Machine", Quality.MIL_SPEC, new Range(0, 0.6)),
            new Skin(Weapon.MAC_10, "Nuclear Garden", Quality.MIL_SPEC, new Range(0, 0.7)),
            new Skin(Weapon.MP9, "Setting Sun", Quality.MIL_SPEC, new Range(0, 1)),
            new Skin(Weapon.AUG, "Radiation Hazard", Quality.INDUSTRIAL, new Range(0, 0.55)),
            new Skin(Weapon.PP_BIZON, "Chemical Green", Quality.INDUSTRIAL, new Range(0, 0.9)),
            new Skin(Weapon.NEGEV, "Nuclear Waste", Quality.INDUSTRIAL, new Range(0, 0.4)),
            new Skin(Weapon.P250, "Contamination", Quality.INDUSTRIAL, new Range(0, 0.83)),
            new Skin(Weapon.FIVE_SEVEN, "Hot Shot", Quality.INDUSTRIAL, new Range(0, 1)),
            new Skin(Weapon.SG_553, "Fallout Warning", Quality.INDUSTRIAL, new Range(0, 0.8))),
    CHOP_SHOP(
            new Skin(Weapon.GLOCK_18, "Twilight Galaxy", Quality.CLASSIFIED, new Range(0, 0.2)),
            new Skin(Weapon.M4A1_S, "Hot Rod", Quality.CLASSIFIED, new Range(0, 0.08)),
            new Skin(Weapon.DUAL_BERETTAS, "Duelist", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.SG_553, "Bulldozer", Quality.RESTRICTED, new Range(0.06, 0.8)),
            new Skin(Weapon.CZ75_AUTO, "Emerald", Quality.MIL_SPEC, new Range(0, 0.08)),
            new Skin(Weapon.FIVE_SEVEN, "Nitro", Quality.MIL_SPEC, new Range(0, 0.8)),
            new Skin(Weapon.MP7, "Full Stop", Quality.MIL_SPEC, new Range(0, 0.6)),
            new Skin(Weapon.P250, "Whiteout", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.MAC_10, "Fade", Quality.MIL_SPEC, new Range(0, 0.4)),
            new Skin(Weapon.USP_S, "Para Green", Quality.INDUSTRIAL, new Range(0, 0.8)),
            new Skin(Weapon.GALIL_AR, "Urban Rubble", Quality.INDUSTRIAL, new Range(0, 1)),
            new Skin(Weapon.DESERT_EAGLE, "Night", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.MAG_7, "Seabird", Quality.CONSUMER, new Range(0, 1)),
            new Skin(Weapon.M249, "Impact Drill", Quality.CONSUMER, new Range(0, 1)),
            new Skin(Weapon.CZ75_AUTO, "Army Sheen", Quality.CONSUMER, new Range(0, 0.3)),
            new Skin(Weapon.SCAR_20, "Army Sheen", Quality.CONSUMER, new Range(0, 0.3))),
    CHROMA(
            new Skin(Weapon.GALIL_AR, "Chatterbox", Quality.COVERT, new Range(0.35, 0.85)),
            new Skin(Weapon.AWP, "Man-o'-war", Quality.COVERT, new Range(0.1, 0.2)),
            new Skin(Weapon.P250, "Muertos", Quality.CLASSIFIED, new Range(0, 0.6)),
            new Skin(Weapon.M4A4, "龍王 (Dragon King)", Quality.CLASSIFIED, new Range(0, 0.75)),
            new Skin(Weapon.AK_47, "Cartel", Quality.CLASSIFIED, new Range(0, 0.75)),
            new Skin(Weapon.MAC_10, "Malachite", Quality.RESTRICTED, new Range(0, 0.5)),
            new Skin(Weapon.SAWED_OFF, "Serenity", Quality.RESTRICTED, new Range(0, 0.5)),
            new Skin(Weapon.DUAL_BERETTAS, "Urban Shock", Quality.RESTRICTED, new Range(0, 0.47)),
            new Skin(Weapon.DESERT_EAGLE, "Naga", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.GLOCK_18, "Catacombs", Quality.MIL_SPEC, new Range(0, 0.5)),
            new Skin(Weapon.M249, "System Lock", Quality.MIL_SPEC, new Range(0, 0.8)),
            new Skin(Weapon.XM1014, "Quicksilver", Quality.MIL_SPEC, new Range(0, 0.5)),
            new Skin(Weapon.MP9, "Deadly Poison", Quality.MIL_SPEC, new Range(0, 1)),
            new Skin(Weapon.SCAR_20, "Grotto", Quality.MIL_SPEC, new Range(0, 0.5))),
    CHROMA_2(
            new Skin(Weapon.MAC_10, "Neon Rider", Quality.COVERT, new Range(0, 0.45)),
            new Skin(Weapon.M4A1_S, "Hyper Beast", Quality.COVERT, new Range(0, 1)),
            new Skin(Weapon.FAMAS, "Djinn", Quality.CLASSIFIED, new Range(0, 1)),
            new Skin(Weapon.GALIL_AR, "Eco", Quality.CLASSIFIED, new Range(0.1, 0.85)),
            new Skin(Weapon.FIVE_SEVEN, "Monkey Business", Quality.CLASSIFIED, new Range(0.1, 0.9)),
            new Skin(Weapon.UMP_45, "Grand Prix", Quality.RESTRICTED, new Range(0.25, 0.35)),
            new Skin(Weapon.CZ75_AUTO, "Pole Position", Quality.RESTRICTED, new Range(0, 0.7)),
            new Skin(Weapon.MAG_7, "Heat", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.AWP, "Worm God", Quality.RESTRICTED, new Range(0, 0.45)),
            new Skin(Weapon.SAWED_OFF, "Origami", Quality.MIL_SPEC, new Range(0, 0.55)),
            new Skin(Weapon.NEGEV, "Man-o'-war", Quality.MIL_SPEC, new Range(0.1, 0.2)),
            new Skin(Weapon.P250, "Valence", Quality.MIL_SPEC, new Range(0, 0.8)),
            new Skin(Weapon.DESERT_EAGLE, "Bronze Deco", Quality.MIL_SPEC, new Range(0, 0.46)),
            new Skin(Weapon.MP7, "Armor Core", Quality.MIL_SPEC, new Range(0, 0.5)),
            new Skin(Weapon.AK_47, "Elite Build", Quality.MIL_SPEC, new Range(0, 1))),
    COBBLESTONE(
            new Skin(Weapon.AWP, "Dragon Lore", Quality.COVERT, new Range(0, 0.7)),
            new Skin(Weapon.M4A1_S, "Knight", Quality.CLASSIFIED, new Range(0, 0.1)),
            new Skin(Weapon.DESERT_EAGLE, "Hand Cannon", Quality.RESTRICTED, new Range(0.01, 0.7)),
            new Skin(Weapon.CZ75_AUTO, "Chalice", Quality.RESTRICTED, new Range(0, 0.1)),
            new Skin(Weapon.MP9, "Dark Age", Quality.MIL_SPEC, new Range(0, 0.22)),
            new Skin(Weapon.P2000, "Chainmail", Quality.MIL_SPEC, new Range(0, 0.22)),
            new Skin(Weapon.USP_S, "Royal Blue", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.NOVA, "Green Apple", Quality.INDUSTRIAL, new Range(0, 0.3)),
            new Skin(Weapon.MAG_7, "Silver", Quality.INDUSTRIAL, new Range(0, 0.08)),
            new Skin(Weapon.SAWED_OFF, "Rust Coat", Quality.INDUSTRIAL, new Range(0, 0.8)),
            new Skin(Weapon.P90, "Storm", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.UMP_45, "Indigo", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.MAC_10, "Indigo", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.SCAR_20, "Storm", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.DUAL_BERETTAS, "Briar", Quality.CONSUMER, new Range(0, 0.22))),
    DUST(
            new Skin(Weapon.GLOCK_18, "Brass", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.P2000, "Scorpion", Quality.RESTRICTED, new Range(0, 0.08)),
            new Skin(Weapon.DESERT_EAGLE, "Blaze", Quality.RESTRICTED, new Range(0, 0.08)),
            new Skin(Weapon.SAWED_OFF, "Copper", Quality.MIL_SPEC, new Range(0, 1)),
            new Skin(Weapon.AUG, "Copperhead", Quality.MIL_SPEC, new Range(0.12, 0.38)),
            new Skin(Weapon.AWP, "Snake Camo", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.AK_47, "Predator", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.SCAR_20, "Palm", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.M4A4, "Desert Storm", Quality.INDUSTRIAL, new Range(0.06, 0.8))),
    DUST_2(
            new Skin(Weapon.R8_REVOLVER, "Amber Fade", Quality.CLASSIFIED, new Range(0, 0.4)),
            new Skin(Weapon.P2000, "Amber Fade", Quality.RESTRICTED, new Range(0, 0.4)),
            new Skin(Weapon.SG_553, "Damascus Steel", Quality.MIL_SPEC, new Range(0, 1)),
            new Skin(Weapon.PP_BIZON, "Brass", Quality.MIL_SPEC, new Range(0, 1)),
            new Skin(Weapon.M4A1_S, "VariCamo", Quality.MIL_SPEC, new Range(0, 0.6)),
            new Skin(Weapon.SAWED_OFF, "Snake Camo", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.AK_47, "Safari Mesh", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.FIVE_SEVEN, "Orange Peel", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.MAC_10, "Palm", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.TEC_9, "VariCamo", Quality.INDUSTRIAL, new Range(0, 0.6)),
            new Skin(Weapon.G3SG1, "Desert Storm", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.P250, "Sand Dune", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.SCAR_20, "Sand Mesh", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.P90, "Sand Spray", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.MP9, "Sand Dashed", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.NOVA, "Predator", Quality.CONSUMER, new Range(0.06, 0.8))),
    ESPORTS_2013(
            new Skin(Weapon.P90, "Death by Kitty", Quality.COVERT, new Range(0.08, 0.32)),
            new Skin(Weapon.AWP, "BOOM", Quality.CLASSIFIED, new Range(0.06, 0.28)),
            new Skin(Weapon.AK_47, "Red Laminate", Quality.CLASSIFIED, new Range(0.06, 0.8)),
            new Skin(Weapon.GALIL_AR, "Orange DDPAT", Quality.RESTRICTED, new Range(0.06, 0.8)),
            new Skin(Weapon.P250, "Splash", Quality.RESTRICTED, new Range(0.06, 0.18)),
            new Skin(Weapon.SAWED_OFF, "Orange DDPAT", Quality.RESTRICTED, new Range(0.06, 0.8)),
            new Skin(Weapon.MAG_7, "Memento", Quality.MIL_SPEC, new Range(0.02, 0.18)),
            new Skin(Weapon.FAMAS, "Doomkitty", Quality.MIL_SPEC, new Range(0.08, 0.22)),
            new Skin(Weapon.M4A4, "Faded Zebra", Quality.MIL_SPEC, new Range(0.06, 0.8))),
    ESPORTS_2013_WINTER(
            new Skin(Weapon.M4A4, "X-Ray", Quality.COVERT, new Range(0, 0.3)),
            new Skin(Weapon.DESERT_EAGLE, "Cobalt Disruption", Quality.CLASSIFIED, new Range(0, 0.2)),
            new Skin(Weapon.AWP, "Electric Hive", Quality.CLASSIFIED, new Range(0, 0.4)),
            new Skin(Weapon.FAMAS, "Afterimage", Quality.CLASSIFIED, new Range(0.02, 0.4)),
            new Skin(Weapon.AK_47, "Blue Laminate", Quality.RESTRICTED, new Range(0.02, 0.4)),
            new Skin(Weapon.P90, "Blind Spot", Quality.RESTRICTED, new Range(0, 0.5)),
            new Skin(Weapon.GALIL_AR, "Blue Titanium", Quality.MIL_SPEC, new Range(0, 0.04)),
            new Skin(Weapon.PP_BIZON, "Water Sigil", Quality.MIL_SPEC, new Range(0, 0.5)),
            new Skin(Weapon.NOVA, "Ghost Camo", Quality.MIL_SPEC, new Range(0, 0.4)),
            new Skin(Weapon.G3SG1, "Azure Zebra", Quality.MIL_SPEC, new Range(0, 0.28)),
            new Skin(Weapon.P250, "Steel Disruption", Quality.MIL_SPEC, new Range(0, 0.2)),
            new Skin(Weapon.FIVE_SEVEN, "Nightshade", Quality.MIL_SPEC, new Range(0, 0.5))),
    ESPORTS_2014_SUMMER(
            new Skin(Weapon.M4A4, "Bullet Rain", Quality.COVERT, new Range(0.02, 0.46)),
            new Skin(Weapon.AK_47, "Jaguar", Quality.COVERT, new Range(0, 1)),
            new Skin(Weapon.P2000, "Corticera", Quality.CLASSIFIED, new Range(0.06, 0.3)),
            new Skin(Weapon.AWP, "Corticera", Quality.CLASSIFIED, new Range(0.06, 0.3)),
            new Skin(Weapon.NOVA, "Bloomstick", Quality.CLASSIFIED, new Range(0.06, 0.8)),
            new Skin(Weapon.AUG, "Bengal Tiger", Quality.CLASSIFIED, new Range(0.06, 0.8)),
            new Skin(Weapon.DESERT_EAGLE, "Crimson Web", Quality.RESTRICTED, new Range(0.06, 0.8)),
            new Skin(Weapon.GLOCK_18, "Steel Disruption", Quality.RESTRICTED, new Range(0, 0.2)),
            new Skin(Weapon.MP7, "Ocean Foam", Quality.RESTRICTED, new Range(0, 0.08)),
            new Skin(Weapon.PP_BIZON, "Blue Streak", Quality.RESTRICTED, new Range(0.06, 0.8)),
            new Skin(Weapon.P90, "Virus", Quality.RESTRICTED, new Range(0.06, 0.8)),
            new Skin(Weapon.XM1014, "Red Python", Quality.MIL_SPEC, new Range(0.08, 0.5)),
            new Skin(Weapon.NEGEV, "Bratatat", Quality.MIL_SPEC, new Range(0, 1)),
            new Skin(Weapon.CZ75_AUTO, "Hexane", Quality.MIL_SPEC, new Range(0, 0.4)),
            new Skin(Weapon.USP_S, "Blood Tiger", Quality.MIL_SPEC, new Range(0, 0.3)),
            new Skin(Weapon.MAC_10, "Ultraviolet", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.SSG_08, "Dark Water", Quality.MIL_SPEC, new Range(0.1, 0.26))),
    FALCHION(
            new Skin(Weapon.AWP, "Hyper Beast", Quality.COVERT, new Range(0, 1)),
            new Skin(Weapon.AK_47, "Aquamarine Revenge", Quality.COVERT, new Range(0, 1)),
            new Skin(Weapon.SG_553, "Cyrex", Quality.CLASSIFIED, new Range(0, 1)),
            new Skin(Weapon.MP7, "Nemesis", Quality.CLASSIFIED, new Range(0, 0.32)),
            new Skin(Weapon.CZ75_AUTO, "Yellow Jacket", Quality.CLASSIFIED, new Range(0, 1)),
            new Skin(Weapon.P2000, "Handgun", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.NEGEV, "Loudmouth", Quality.RESTRICTED, new Range(0.14, 0.65)),
            new Skin(Weapon.MP9, "Ruby Poison Dart", Quality.RESTRICTED, new Range(0, 0.5)),
            new Skin(Weapon.M4A4, "Evil Daimyo", Quality.RESTRICTED, new Range(0, 0.52)),
            new Skin(Weapon.FAMAS, "Neural Net", Quality.RESTRICTED, new Range(0, 0.6)),
            new Skin(Weapon.USP_S, "Torque", Quality.MIL_SPEC, new Range(0, 0.46)),
            new Skin(Weapon.UMP_45, "Riot", Quality.MIL_SPEC, new Range(0, 0.7)),
            new Skin(Weapon.P90, "Elite Build", Quality.MIL_SPEC, new Range(0, 1)),
            new Skin(Weapon.NOVA, "Ranger", Quality.MIL_SPEC, new Range(0, 1)),
            new Skin(Weapon.GLOCK_18, "Bunsen Burner", Quality.MIL_SPEC, new Range(0, 0.8)),
            new Skin(Weapon.GALIL_AR, "Rocket Pop", Quality.MIL_SPEC, new Range(0, 1))),
    GODS_AND_MONSTERS(
            new Skin(Weapon.AWP, "Medusa", Quality.COVERT, new Range(0, 1)),
            new Skin(Weapon.M4A4, "Poseidon", Quality.CLASSIFIED, new Range(0, 0.33)),
            new Skin(Weapon.G3SG1, "Chronos", Quality.RESTRICTED, new Range(0, 0.4)),
            new Skin(Weapon.M4A1_S, "Icarus Fell", Quality.RESTRICTED, new Range(0, 0.1)),
            new Skin(Weapon.UMP_45, "Minotaur's Labyrinth", Quality.MIL_SPEC, new Range(0, 0.39)),
            new Skin(Weapon.MP9, "Pandora's Box", Quality.MIL_SPEC, new Range(0, 0.3)),
            new Skin(Weapon.TEC_9, "Hades", Quality.INDUSTRIAL, new Range(0, 1)),
            new Skin(Weapon.P2000, "Pathfinder", Quality.INDUSTRIAL, new Range(0, 0.35)),
            new Skin(Weapon.AWP, "Sun in Leo", Quality.INDUSTRIAL, new Range(0, 0.5)),
            new Skin(Weapon.M249, "Shipping Forecast", Quality.INDUSTRIAL, new Range(0, 0.5)),
            new Skin(Weapon.MP7, "Asterion", Quality.CONSUMER, new Range(0, 0.55)),
            new Skin(Weapon.AUG, "Daedalus", Quality.CONSUMER, new Range(0, 0.55)),
            new Skin(Weapon.DUAL_BERETTAS, "Moon in Libra", Quality.CONSUMER, new Range(0, 0.5)),
            new Skin(Weapon.NOVA, "Moon in Libra", Quality.CONSUMER, new Range(0, 0.5))),
    HUNTSMAN(
            new Skin(Weapon.M4A4, "Desert-Strike", Quality.COVERT, new Range(0, 0.7)),
            new Skin(Weapon.AK_47, "Vulcan", Quality.COVERT, new Range(0, 0.9)),
            new Skin(Weapon.USP_S, "Caiman", Quality.CLASSIFIED, new Range(0, 0.4)),
            new Skin(Weapon.M4A1_S, "Atomic Alloy", Quality.CLASSIFIED, new Range(0, 0.9)),
            new Skin(Weapon.SCAR_20, "Cyrex", Quality.CLASSIFIED, new Range(0, 0.5)),
            new Skin(Weapon.USP_S, "Orion", Quality.CLASSIFIED, new Range(0, 0.5)),
            new Skin(Weapon.MAC_10, "Tatter", Quality.RESTRICTED, new Range(0, 0.5)),
            new Skin(Weapon.AUG, "Torque", Quality.RESTRICTED, new Range(0, 0.5)),
            new Skin(Weapon.PP_BIZON, "Antique", Quality.RESTRICTED, new Range(0, 0.5)),
            new Skin(Weapon.MAC_10, "Curse", Quality.RESTRICTED, new Range(0, 0.5)),
            new Skin(Weapon.XM1014, "Heaven Guard", Quality.RESTRICTED, new Range(0.03, 0.5)),
            new Skin(Weapon.CZ75_AUTO, "Twist", Quality.MIL_SPEC, new Range(0, 1)),
            new Skin(Weapon.P90, "Module", Quality.MIL_SPEC, new Range(0, 0.35)),
            new Skin(Weapon.P2000, "Pulse", Quality.MIL_SPEC, new Range(0, 0.6)),
            new Skin(Weapon.TEC_9, "Isaac", Quality.MIL_SPEC, new Range(0, 1)),
            new Skin(Weapon.SSG_08, "Slashed", Quality.MIL_SPEC, new Range(0.15, 0.8)),
            new Skin(Weapon.DUAL_BERETTAS, "Retribution", Quality.MIL_SPEC, new Range(0, 0.45)),
            new Skin(Weapon.GALIL_AR, "Kami", Quality.MIL_SPEC, new Range(0, 0.6)),
            new Skin(Weapon.P90, "Desert Warfare", Quality.MIL_SPEC, new Range(0, 0.5)),
            new Skin(Weapon.CZ75_AUTO, "Poison Dart", Quality.MIL_SPEC, new Range(0, 0.7))),
    INFERNO(
            new Skin(Weapon.TEC_9, "Brass", Quality.MIL_SPEC, new Range(0, 1)),
            new Skin(Weapon.DUAL_BERETTAS, "Anodized Navy", Quality.MIL_SPEC, new Range(0, 0.08)),
            new Skin(Weapon.M4A4, "Tornado", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.P250, "Gunsmoke", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.NOVA, "Walnut", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.MAG_7, "Sand Dune", Quality.CONSUMER, new Range(0.06, 0.8))),
    ITALY(
            new Skin(Weapon.AWP, "Pit Viper", Quality.RESTRICTED, new Range(0.08, 0.5)),
            new Skin(Weapon.SAWED_OFF, "Full Stop", Quality.MIL_SPEC, new Range(0, 0.6)),
            new Skin(Weapon.GLOCK_18, "Candy Apple", Quality.MIL_SPEC, new Range(0, 0.3)),
            new Skin(Weapon.MP7, "Anodized Navy", Quality.MIL_SPEC, new Range(0, 0.08)),
            new Skin(Weapon.XM1014, "CaliCamo", Quality.INDUSTRIAL, new Range(0, 0.6)),
            new Skin(Weapon.M4A1_S, "Boreal Forest", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.UMP_45, "Gunsmoke", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.P2000, "Granite Marbleized", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.DUAL_BERETTAS, "Stained", Quality.INDUSTRIAL, new Range(0, 1)),
            new Skin(Weapon.NOVA, "Candy Apple", Quality.INDUSTRIAL, new Range(0, 0.3)),
            new Skin(Weapon.TEC_9, "Groundwater", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.AUG, "Contractor", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.FAMAS, "Colony", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.NOVA, "Sand Dune", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.PP_BIZON, "Sand Dashed", Quality.CONSUMER, new Range(0.06, 0.8))),
    LAKE(
            new Skin(Weapon.DUAL_BERETTAS, "Cobalt Quartz", Quality.RESTRICTED, new Range(0, 0.4)),
            new Skin(Weapon.USP_S, "Night Ops", Quality.MIL_SPEC, new Range(0, 0.6)),
            new Skin(Weapon.P90, "Teardown", Quality.MIL_SPEC, new Range(0, 0.6)),
            new Skin(Weapon.SG_553, "Anodized Navy", Quality.MIL_SPEC, new Range(0, 0.08)),
            new Skin(Weapon.DESERT_EAGLE, "Mudder", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.AWP, "Safari Mesh", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.PP_BIZON, "Night Ops", Quality.INDUSTRIAL, new Range(0, 0.6)),
            new Skin(Weapon.FAMAS, "Cyanospatter", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.XM1014, "Blue Steel", Quality.INDUSTRIAL, new Range(0, 1)),
            new Skin(Weapon.P250, "Boreal Forest", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.XM1014, "Blue Spruce", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.AUG, "Storm", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.GALIL_AR, "Sage Spray", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.SG_553, "Waves Perforated", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.G3SG1, "Jungle Dashed", Quality.CONSUMER, new Range(0.06, 0.8))),
    MILITIA(
            new Skin(Weapon.SCAR_20, "Splash Jam", Quality.CLASSIFIED, new Range(0.06, 0.8)),
            new Skin(Weapon.M4A4, "Modern Hunter", Quality.RESTRICTED, new Range(0.06, 0.8)),
            new Skin(Weapon.NOVA, "Modern Hunter", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.PP_BIZON, "Modern Hunter", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.XM1014, "Blaze Orange", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.P250, "Modern Hunter", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.NOVA, "Blaze Orange", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.P2000, "Grassland Leaves", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.PP_BIZON, "Forest Leaves", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.MAC_10, "Tornado", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.XM1014, "Grassland", Quality.CONSUMER, new Range(0.06, 0.8))),
    MIRAGE(
            new Skin(Weapon.MAG_7, "Bulldozer", Quality.RESTRICTED, new Range(0.06, 0.8)),
            new Skin(Weapon.MAC_10, "Amber Fade", Quality.MIL_SPEC, new Range(0, 0.4)),
            new Skin(Weapon.UMP_45, "Blaze", Quality.MIL_SPEC, new Range(0, 0.08)),
            new Skin(Weapon.MP9, "Hot Rod", Quality.MIL_SPEC, new Range(0, 0.08)),
            new Skin(Weapon.NEGEV, "CaliCamo", Quality.INDUSTRIAL, new Range(0, 0.6)),
            new Skin(Weapon.SSG_08, "Tropical Storm", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.SG_553, "Gator Mesh", Quality.INDUSTRIAL, new Range(0, 0.6)),
            new Skin(Weapon.GLOCK_18, "Groundwater", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.MP7, "Orange Peel", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.P250, "Bone Mask", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.FIVE_SEVEN, "Contractor", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.AUG, "Colony", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.G3SG1, "Safari Mesh", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.P90, "Scorched", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.GALIL_AR, "Hunting Blind", Quality.CONSUMER, new Range(0, 0.6))),
    NUKE(
            new Skin(Weapon.TEC_9, "Nuclear Threat", Quality.RESTRICTED, new Range(0.06, 0.8)),
            new Skin(Weapon.P250, "Nuclear Threat", Quality.RESTRICTED, new Range(0.06, 0.8)),
            new Skin(Weapon.M4A4, "Radiation Hazard", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.XM1014, "Fallout Warning", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.UMP_45, "Fallout Warning", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.P90, "Fallout Warning", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.PP_BIZON, "Irradiated Alert", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.SAWED_OFF, "Irradiated Alert", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.MAG_7, "Irradiated Alert", Quality.CONSUMER, new Range(0.06, 0.8))),
    OFFICE(
            new Skin(Weapon.MP7, "Whiteout", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.P2000, "Silver", Quality.MIL_SPEC, new Range(0.0, 0.08)),
            new Skin(Weapon.M249, "Blizzard Marbleized", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.G3SG1, "Arctic Camo", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.GALIL_AR, "Winter Forest", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.FAMAS, "Contrast Spray", Quality.CONSUMER, new Range(0.06, 0.8))),
    OVERPASS(
            new Skin(Weapon.M4A1_S, "Master Piece", Quality.CLASSIFIED, new Range(0, 1)),
            new Skin(Weapon.AWP, "Pink DDPAT", Quality.RESTRICTED, new Range(0.06, 0.8)),
            new Skin(Weapon.USP_S, "Road Rash", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.SSG_08, "Detour", Quality.MIL_SPEC, new Range(0, 0.43)),
            new Skin(Weapon.XM1014, "VariCamo Blue", Quality.MIL_SPEC, new Range(0, 0.5)),
            new Skin(Weapon.CZ75_AUTO, "Nitro", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.DESERT_EAGLE, "Urban DDPAT", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.MP7, "Gunsmoke", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.P2000, "Grassland", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.GLOCK_18, "Night", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.UMP_45, "Scorched", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.M249, "Contrast Spray", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.MAG_7, "Storm", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.MP9, "Storm", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.SAWED_OFF, "Sage Spray", Quality.CONSUMER, new Range(0.06, 0.8))),
    PHOENIX(
            new Skin(Weapon.AUG, "Chameleon", Quality.COVERT, new Range(0, 0.5)),
            new Skin(Weapon.AWP, "Asiimov", Quality.COVERT, new Range(0.18, 1)),
            new Skin(Weapon.P90, "Trigon", Quality.CLASSIFIED, new Range(0.08, 0.75)),
            new Skin(Weapon.AK_47, "Redline", Quality.CLASSIFIED, new Range(0.1, 0.7)),
            new Skin(Weapon.NOVA, "Antique", Quality.CLASSIFIED, new Range(0, 0.3)),
            new Skin(Weapon.SG_553, "Pulse", Quality.RESTRICTED, new Range(0.1, 0.6)),
            new Skin(Weapon.MAC_10, "Heat", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.FAMAS, "Sergeant", Quality.RESTRICTED, new Range(0.1, 1)),
            new Skin(Weapon.USP_S, "Guardian", Quality.RESTRICTED, new Range(0, 0.38)),
            new Skin(Weapon.TEC_9, "Sandstorm", Quality.MIL_SPEC, new Range(0.1, 0.7)),
            new Skin(Weapon.MAG_7, "Heaven Guard", Quality.MIL_SPEC, new Range(0.0, 0.4)),
            new Skin(Weapon.UMP_45, "Corporal", Quality.MIL_SPEC, new Range(0.05, 0.75)),
            new Skin(Weapon.NEGEV, "Terrain", Quality.MIL_SPEC, new Range(0, 0.45))),
    REVOLVER(
            new Skin(Weapon.R8_REVOLVER, "Fade", Quality.COVERT, new Range(0, 0.4)),
            new Skin(Weapon.M4A4, "Royal Paladin", Quality.COVERT, new Range(0, 0.8)),
            new Skin(Weapon.P90, "Shapewood", Quality.CLASSIFIED, new Range(0, 1)),
            new Skin(Weapon.G3SG1, "The Executioner", Quality.CLASSIFIED, new Range(0.14, 0.85)),
            new Skin(Weapon.AK_47, "Point Disarray", Quality.CLASSIFIED, new Range(0, 0.67)),
            new Skin(Weapon.FIVE_SEVEN, "Retrobution", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.NEGEV, "Power Loader", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.PP_BIZON, "Fuel Rod", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.SG_553, "Tiger Moth", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.XM1014, "Teclu Burner", Quality.RESTRICTED, new Range(0, 0.65)),
            new Skin(Weapon.TEC_9, "Avalanche", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.SCAR_20, "Outbreak", Quality.MIL_SPEC, new Range(0, 0.5)),
            new Skin(Weapon.SAWED_OFF, "Yorick", Quality.MIL_SPEC, new Range(0, 1)),
            new Skin(Weapon.DESERT_EAGLE, "Corinthian", Quality.MIL_SPEC, new Range(0, 0.44)),
            new Skin(Weapon.AUG, "Ricochet", Quality.MIL_SPEC, new Range(0, 0.8)),
            new Skin(Weapon.P2000, "Imperial", Quality.MIL_SPEC, new Range(0, 0.2)),
            new Skin(Weapon.R8_REVOLVER, "Crimson Web", Quality.MIL_SPEC, new Range(0.06, 0.8))),
    RISING_SUN(
            new Skin(Weapon.AUG, "Akihabara Accept", Quality.COVERT, new Range(0, 1)),
            new Skin(Weapon.AK_47, "Hydroponic", Quality.CLASSIFIED, new Range(0, 0.8)),
            new Skin(Weapon.DESERT_EAGLE, "Sunset Storm 壱", Quality.RESTRICTED, new Range(0, 0.75)),
            new Skin(Weapon.FIVE_SEVEN, "Neon Kimono", Quality.RESTRICTED, new Range(0, 0.8)),
            new Skin(Weapon.DESERT_EAGLE, "Sunset Storm 弐", Quality.RESTRICTED, new Range(0, 0.75)),
            new Skin(Weapon.M4A4, "Daybreak", Quality.RESTRICTED, new Range(0, 0.6)),
            new Skin(Weapon.MAG_7, "Counter Terrace", Quality.MIL_SPEC, new Range(0, 0.65)),
            new Skin(Weapon.TEC_9, "Terrace", Quality.MIL_SPEC, new Range(0, 1)),
            new Skin(Weapon.GALIL_AR, "Aqua Terrace", Quality.MIL_SPEC, new Range(0, 0.7)),
            new Skin(Weapon.DESERT_EAGLE, "Midnight Storm", Quality.INDUSTRIAL, new Range(0, 0.75)),
            new Skin(Weapon.P250, "Crimson Kimono", Quality.INDUSTRIAL, new Range(0, 0.8)),//x*.8 < .15
            new Skin(Weapon.PP_BIZON, "Bamboo Print", Quality.CONSUMER, new Range(0, 0.8)),
            new Skin(Weapon.P250, "Mint Kimono", Quality.CONSUMER, new Range(0, 0.8)),
            new Skin(Weapon.SAWED_OFF, "Bamboo Shadow", Quality.CONSUMER, new Range(0, 0.6)),
            new Skin(Weapon.TEC_9, "Bamboo Forest", Quality.CONSUMER, new Range(0, 0.6)),
            new Skin(Weapon.G3SG1, "Orange Kimono", Quality.CONSUMER, new Range(0, 0.8))),
    SAFEHOUSE(
            new Skin(Weapon.M4A1_S, "Nitro", Quality.RESTRICTED, new Range(0.06, 0.8)),
            new Skin(Weapon.FAMAS, "Teardown", Quality.MIL_SPEC, new Range(0, 0.6)),
            new Skin(Weapon.FIVE_SEVEN, "Silver Quartz", Quality.MIL_SPEC, new Range(0, 0.4)),
            new Skin(Weapon.SSG_08, "Acid Fade", Quality.MIL_SPEC, new Range(0, 0.03)),
            new Skin(Weapon.G3SG1, "VariCamo", Quality.INDUSTRIAL, new Range(0, 0.6)),
            new Skin(Weapon.M249, "Gator Mesh", Quality.INDUSTRIAL, new Range(0, 0.6)),
            new Skin(Weapon.GALIL_AR, "VariCamo", Quality.INDUSTRIAL, new Range(0, 0.6)),
            new Skin(Weapon.USP_S, "Forest Leaves", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.AUG, "Condemned", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.MP9, "Orange Peel", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.SSG_08, "Blue Spruce", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.MP7, "Army Recon", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.SCAR_20, "Contractor", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.DUAL_BERETTAS, "Contractor", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.TEC_9, "Army Mesh", Quality.CONSUMER, new Range(0, 0.6))),
    SHADOW(
            new Skin(Weapon.M4A1_S, "Golden Coil", Quality.COVERT, new Range(0, 1)),
            new Skin(Weapon.USP_S, "Kill Confirmed", Quality.COVERT, new Range(0, 1)),
            new Skin(Weapon.AK_47, "Frontside Misty", Quality.CLASSIFIED, new Range(0.02, 0.87)),
            new Skin(Weapon.G3SG1, "Flux", Quality.CLASSIFIED, new Range(0, 0.9)),
            new Skin(Weapon.SSG_08, "Big Iron", Quality.CLASSIFIED, new Range(0, 0.64)),
            new Skin(Weapon.GALIL_AR, "Stone Cold", Quality.RESTRICTED, new Range(0, 0.9)),
            new Skin(Weapon.MP7, "Special Delivery", Quality.RESTRICTED, new Range(0, 0.62)),
            new Skin(Weapon.P250, "Wingshot", Quality.RESTRICTED, new Range(0, 0.9)),
            new Skin(Weapon.M249, "Nebula Crusader", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.FAMAS, "Survivor Z", Quality.MIL_SPEC, new Range(0, 0.6)),
            new Skin(Weapon.DUAL_BERETTAS, "Dualing Dragons", Quality.MIL_SPEC, new Range(0, 1)),
            new Skin(Weapon.GLOCK_18, "Wraiths", Quality.MIL_SPEC, new Range(0, 0.8)),
            new Skin(Weapon.MAC_10, "Rangeen", Quality.MIL_SPEC, new Range(0, 0.5)),
            new Skin(Weapon.SCAR_20, "Green Marine", Quality.MIL_SPEC, new Range(0, 0.8)),
            new Skin(Weapon.MAG_7, "Cobalt Core", Quality.MIL_SPEC, new Range(0, 0.5)),
            new Skin(Weapon.XM1014, "Scumbria", Quality.MIL_SPEC, new Range(0, 1))),
    TRAIN(
            new Skin(Weapon.TEC_9, "Red Quartz", Quality.RESTRICTED, new Range(0, 0.4)),
            new Skin(Weapon.SAWED_OFF, "Amber Fade", Quality.MIL_SPEC, new Range(0, 0.4)),
            new Skin(Weapon.DESERT_EAGLE, "Urban Rubble", Quality.MIL_SPEC, new Range(0, 0.5)),
            new Skin(Weapon.P90, "Ash Wood", Quality.INDUSTRIAL, new Range(0, 0.45)),
            new Skin(Weapon.MAG_7, "Metallic DDPAT", Quality.INDUSTRIAL, new Range(0, 0.08)),
            new Skin(Weapon.MAC_10, "Candy Apple", Quality.INDUSTRIAL, new Range(0, 0.3)),
            new Skin(Weapon.M4A4, "Urban DDPAT", Quality.INDUSTRIAL, new Range(0.06, 0.8)),
            new Skin(Weapon.SCAR_20, "Carbon Fiber", Quality.INDUSTRIAL, new Range(0, 0.12)),
            new Skin(Weapon.P250, "Metallic DDPAT", Quality.INDUSTRIAL, new Range(0, 0.08)),
            new Skin(Weapon.UMP_45, "Urban DDPAT", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.DUAL_BERETTAS, "Colony", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.NOVA, "Polar Mesh", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.G3SG1, "Polar Camo", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.FIVE_SEVEN, "Forest Night", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.PP_BIZON, "Urban Dashed", Quality.CONSUMER, new Range(0.06, 0.8))),
    VANGUARD(
            new Skin(Weapon.AK_47, "Wasteland Rebel", Quality.COVERT, new Range(0.05, 0.7)),
            new Skin(Weapon.P2000, "Fire Elemental", Quality.COVERT, new Range(0, 0.6)),
            new Skin(Weapon.XM1014, "Tranquility", Quality.CLASSIFIED, new Range(0, 0.5)),
            new Skin(Weapon.SCAR_20, "Cardiac", Quality.CLASSIFIED, new Range(0, 1)),
            new Skin(Weapon.P250, "Cartel", Quality.CLASSIFIED, new Range(0, 0.75)),
            new Skin(Weapon.GLOCK_18, "Grinder", Quality.RESTRICTED, new Range(0.02, 0.25)),
            new Skin(Weapon.SAWED_OFF, "Highwayman", Quality.RESTRICTED, new Range(0, 1)),
            new Skin(Weapon.M4A4, "Griffin", Quality.RESTRICTED, new Range(0, 0.8)),
            new Skin(Weapon.M4A1_S, "Basilisk", Quality.RESTRICTED, new Range(0, 0.68)),
            new Skin(Weapon.MP9, "Dart", Quality.MIL_SPEC, new Range(0, 0.46)),
            new Skin(Weapon.MAG_7, "Firestarter", Quality.MIL_SPEC, new Range(0.06, 0.49)),
            new Skin(Weapon.FIVE_SEVEN, "Urban Hazard", Quality.MIL_SPEC, new Range(0, 0.25)),
            new Skin(Weapon.UMP_45, "Delusion", Quality.MIL_SPEC, new Range(0.06, 0.35)),
            new Skin(Weapon.G3SG1, "Murky", Quality.MIL_SPEC, new Range(0, 0.25))),
    VERTIGO(
            new Skin(Weapon.DUAL_BERETTAS, "Demolition", Quality.RESTRICTED, new Range(0.26, 0.6)),
            new Skin(Weapon.P90, "Glacier Mesh", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.AK_47, "Black Laminate", Quality.MIL_SPEC, new Range(0.06, 0.8)),
            new Skin(Weapon.PP_BIZON, "Carbon Fiber", Quality.MIL_SPEC, new Range(0, 0.12)),
            new Skin(Weapon.XM1014, "Urban Perforated", Quality.CONSUMER, new Range(0.06, 0.8)),
            new Skin(Weapon.MAC_10, "Urban DDPAT", Quality.CONSUMER, new Range(0.06, 0.8))),
    WINTER_OFFENSIVE(
            new Skin(Weapon.M4A4, "Asiimov", Quality.COVERT, new Range(0.18, 1)),
            new Skin(Weapon.SAWED_OFF, "The Kraken", Quality.COVERT, new Range(0, 0.4)),
            new Skin(Weapon.M4A1_S, "Guardian", Quality.CLASSIFIED, new Range(0, 0.5)),
            new Skin(Weapon.AWP, "Redline", Quality.CLASSIFIED, new Range(0.1, 0.4)),
            new Skin(Weapon.P250, "Mehndi", Quality.CLASSIFIED, new Range(0, 1)),
            new Skin(Weapon.NOVA, "Rising Skull", Quality.RESTRICTED, new Range(0, 0.5)),
            new Skin(Weapon.DUAL_BERETTAS, "Marina", Quality.RESTRICTED, new Range(0.05, 0.5)),
            new Skin(Weapon.MP9, "Rose Iron", Quality.RESTRICTED, new Range(0, 0.3)),
            new Skin(Weapon.FAMAS, "Pulse", Quality.RESTRICTED, new Range(0, 0.4)),
            new Skin(Weapon.FIVE_SEVEN, "Kami", Quality.MIL_SPEC, new Range(0, 0.3)),
            new Skin(Weapon.PP_BIZON, "Cobalt Halftone", Quality.MIL_SPEC, new Range(0.05, 0.45)),
            new Skin(Weapon.GALIL_AR, "Sandstorm", Quality.MIL_SPEC, new Range(0.1, 0.6)),
            new Skin(Weapon.M249, "Magma", Quality.MIL_SPEC, new Range(0, 0.7)));

    private Set<Skin> skins;
    private Set<Item> items = new HashSet<>();

    Collections(Skin...skins) {
        this.skins = new HashSet<>(Arrays.asList(skins));
    }

    @Override
    public String getName() {
        return this.name();
    }

    @Override
    public Set<Skin> getSkins() {
        return this.skins;
    }

    @Override
    public Set<Item> getItems() {
        return this.items;
    }

    @Override
    public void addItem(Item item) {
        this.items.add(item);
    }

}
